#!/usr/bin/env php
<?php

defined('HP_DEBUG') or define('HP_DEBUG', true);
defined('PATH') or define('PATH', __DIR__);

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/core/Core.php');
$config = require(__DIR__ . '/common/config/main.php');


$app = new core\Application($config);
$exitCode = $app->run();